
spring:
  # Aggiungi questo blocco per la connessione!
  rabbitmq:
    host: localhost        # Cambialo se RabbitMQ è su un altro server/IP
    port: 5672             # La porta standard AMQP
    username: user
    password: password
  application:
    name: OrderManagementService
  cloud:
    function:
      definition: orderManagement;orderManagementError
    stream:
      bindings:
        orderOrchestrationService-out-0:
          destination: orders-orchestration-service
          group: queue
        orderOrchestrationServiceError-out-0:
          destination: orders-orchestration-service-error
          group: queue

        #queste sono le code a cui mi sottoscrivo per ricevere l'aggiornamento dell'ordine e/o errori
        orderManagement-in-0:
          destination: order-service
          group: queue
        orderManagementError-in-0:
          destination: order-service-errors
          group: queue
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081